CELL_SIZE = 80

BOARD_SIZE = 8
BOARD_IMAGE_PATH = "assets/board.png"
PIECES_FOLDER = "pieces1"
ESC_KEY = 27

TEXT_COLOR_WHITE = (255, 255, 255, 255)
TEXT_COLOR_RED = (0, 0, 255, 255)

TOP_MARGIN = 60
SIDE_MARGIN = 260
CANVAS_WIDTH = CELL_SIZE * BOARD_SIZE + SIDE_MARGIN
CANVAS_HEIGHT = CELL_SIZE * BOARD_SIZE + TOP_MARGIN
BOARD_OFFSET_X = 0
BOARD_OFFSET_Y = TOP_MARGIN

LOG_PANEL_X = CELL_SIZE * BOARD_SIZE + BOARD_OFFSET_X + 10
LOG_LINE_HEIGHT = 22
LOG_FONT_SIZE = 0.5
